---
- name: Core cluster deployment on core node
  hosts: core-servers
  vars:
    cluster_home: /opt/mindmaps/cluster
    log_home: /var/log/mindmaps/cluster
    storm_daemons: [supervisor]
    database: cassandra
    cassandra_num_tokens: 256
    #cassandra_seeds: [ 127.0.0.1 ]
    cassandra_data_dir: /var/lib/cassandra/data
    cassandra_commitlog_dir: /var/lib/cassandra/commitlog
    cassandra_saved_caches_dir: /var/lib/cassandra/saved_caches
  remote_user: root
  sudo: yes
  
  roles:
     - common
     - storm
     - cassandra
     - supervisor
