---
- name: Core cluster deployment on GM node
  hosts: graph-servers
  vars:
    cluster_home: /opt/mindmaps/cluster
    log_home: /var/log/mindmaps/cluster
    storm_daemons: [nimbus]
    database: none
  remote_user: kasper
  sudo: yes
  
  roles:
     - common
     - storm
     - supervisor
