---
- name: Core cluster deployment on GM node
  hosts: localhost
  vars:
    cluster_home: /opt/mindmaps/cluster
    log_home: /var/log/mindmaps/cluster
    storm_daemons: [nimbus, supervisor]
  remote_user: root
  sudo: yes
  
  roles:
     - core-cluster
