---
- name: Setup zoo.cfg
  template: dest="{{zookeeper_server_dir}}/conf/zoo.cfg" owner={{user_name}} group={{group_name}} src=zoo.cfg.j2

- name: Configure supervisord
  template: dest=/etc/supervisor/supervisor.conf owner={{user_name}} group={{group_name}} src=supervisor.conf.j2

- name: Configure storm
  template: dest="{{storm_server_dir}}/conf/storm.yaml" owner={{user_name}} group={{group_name}} src=storm.yaml.j2

