---
- name: Create log and local directories
  file: path={{item}} state=directory owner={{user_name}} group={{group_name}} mode=664
  with_items:
    - "{{cluster_home}}/neo4j"
    - "{{log_home}}/neo4j"

- stat: path={{ cluster_home }}/{{ neo4j_tarball_name }}
  register: neo4j_tarball

- name: Fetch neo4j package
  get_url: dest={{ cluster_home }}/{{ neo4j_tarball_name }} url={{neo4j_dropbox_link}}
  when: neo4j_tarball.stat.exists == False

- name: ls cluster home
  find: paths={{cluster_home}} recurse=no

- name: Uncompress the neo4j tar
  unarchive: copy=no  dest={{cluster_home}} src={{cluster_home}}/{{neo4j_tarball_name}}

- name: Mv to server
  command: mv {{cluster_home}}/neo4j-enterprise-{{neo4j_version}} {{cluster_home}}/neo4j/server

- name: Copy Neo4j server
  copy: src={{cluster_home}}/neo4j/server dst={{cluster_home}}/neo4j/server owner={{user_name}} group={{group_name}}
 
- name: Set  server dir
  set_fact: neo4j_server_dir="{{cluster_home}}/neo4j/server"
