---
#### Global settings ####

host_address: "{{ansible_default_ipv4.address}}"
root_dir: /opt
cluster_path: mindmaps/cluster
cluster_home: "{{root_dir}}/{{cluster_path}}"
log_home : "/var/log/{{cluster_path}}"

#user and group running the cluster
user_name: mindmaps
group_name: mindmaps

#### ZOOKEEPER settings ####
      
zk_version: 3.4.7
zk_mirror: "http://mirrors.muzzy.org.uk/apache/zookeeper/zookeeper-{{zk_version}}"
zk_tarball_name: "zookeeper-{{zk_version}}.tar.gz"

zookeeper_client_port: 2181
zookeeper_hosts: "{{host_address}}:2181"

zookeeper_dataDir: "{{cluster_home}}/zookeeper"
#zookeeper_dataLogDir:

zookeeper_maxClientCnxns: 60
zookeeper_tick_time: 2000
zookeeper_init_limit: 5
zookeeper_sync_limit: 2

zookeeper_purge_interval: 24
zookeeper_snap_retain_count: 3

#### STORM settings ####

storm_version: 0.9.5
storm_mirror: http://apache.mirrors.tds.net
storm_tarball_name: "apache-storm-{{storm_version}}.tar.gz"

##include as role variable
storm_daemons: [nimbus, supervisor, ui, drpc]
nimbus_host: "{{host_address}}"
drpc_hosts: "{{host_address}}"

nimbus_thrift_port: 6627
storm_drpc_extra_config:
storm_local_dir: "{{cluster_home}}/storm/local"
storm_java_library_path: "/usr/local/lib:/opt/local/lib:/usr/lib"
storm_zookeeper_port: "{{zookeeper_client_port}}"
storm_nimbus_extra_config:
    nimbus.childopts: "-Xmx4g "
storm_supervisor_extra_config:
    supervisor.childopts: "-Xmx4g "
storm_topology_extra_config:
    topology.acker.executors: 1
    topology.debug: false
storm_transactional_extra_config:
    transactional.zookeeper.port: "{{ storm_zookeeper_port }}"
    transactional.zookeeper.root: "/storm-transactional"

storm_ui_port: 8081
storm_ui_extra_config:
    ui.childopts: "-Xmx768m"
storm_worker_extra_config:
    worker.childopts: "-Xmx4g -XX:+UseConcMarkSweepGC -Dcom.sun.management.jmxremote"
storm_worker_ports: [6700, 6701, 6702, 6703]
storm_zookeeper_extra_config:
    storm.zookeeper.port:  "{{ storm_zookeeper_port }}"
    storm.zookeeper.retry.interval: 5000
    storm.zookeeper.retry.times: 60
    storm.zookeeper.root: "/storm"
    storm.zookeeper.session.timeout: 3000
